// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"radioatelier/ent/objectuser"
	"radioatelier/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ObjectUserDelete is the builder for deleting a ObjectUser entity.
type ObjectUserDelete struct {
	config
	hooks    []Hook
	mutation *ObjectUserMutation
}

// Where appends a list predicates to the ObjectUserDelete builder.
func (oud *ObjectUserDelete) Where(ps ...predicate.ObjectUser) *ObjectUserDelete {
	oud.mutation.Where(ps...)
	return oud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (oud *ObjectUserDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, ObjectUserMutation](ctx, oud.sqlExec, oud.mutation, oud.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (oud *ObjectUserDelete) ExecX(ctx context.Context) int {
	n, err := oud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (oud *ObjectUserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(objectuser.Table, nil)
	if ps := oud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, oud.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	oud.mutation.done = true
	return affected, err
}

// ObjectUserDeleteOne is the builder for deleting a single ObjectUser entity.
type ObjectUserDeleteOne struct {
	oud *ObjectUserDelete
}

// Where appends a list predicates to the ObjectUserDelete builder.
func (oudo *ObjectUserDeleteOne) Where(ps ...predicate.ObjectUser) *ObjectUserDeleteOne {
	oudo.oud.mutation.Where(ps...)
	return oudo
}

// Exec executes the deletion query.
func (oudo *ObjectUserDeleteOne) Exec(ctx context.Context) error {
	n, err := oudo.oud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{objectuser.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (oudo *ObjectUserDeleteOne) ExecX(ctx context.Context) {
	if err := oudo.Exec(ctx); err != nil {
		panic(err)
	}
}
