// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"radioatelier/ent/object"
	"radioatelier/ent/objectuser"
	"radioatelier/ent/predicate"
	"radioatelier/ent/schema/puuid"
	"radioatelier/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ObjectUserQuery is the builder for querying ObjectUser entities.
type ObjectUserQuery struct {
	config
	ctx        *QueryContext
	order      []OrderFunc
	inters     []Interceptor
	predicates []predicate.ObjectUser
	withUser   *UserQuery
	withObject *ObjectQuery
	modifiers  []func(*sql.Selector)
	loadTotal  []func(context.Context, []*ObjectUser) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ObjectUserQuery builder.
func (ouq *ObjectUserQuery) Where(ps ...predicate.ObjectUser) *ObjectUserQuery {
	ouq.predicates = append(ouq.predicates, ps...)
	return ouq
}

// Limit the number of records to be returned by this query.
func (ouq *ObjectUserQuery) Limit(limit int) *ObjectUserQuery {
	ouq.ctx.Limit = &limit
	return ouq
}

// Offset to start from.
func (ouq *ObjectUserQuery) Offset(offset int) *ObjectUserQuery {
	ouq.ctx.Offset = &offset
	return ouq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ouq *ObjectUserQuery) Unique(unique bool) *ObjectUserQuery {
	ouq.ctx.Unique = &unique
	return ouq
}

// Order specifies how the records should be ordered.
func (ouq *ObjectUserQuery) Order(o ...OrderFunc) *ObjectUserQuery {
	ouq.order = append(ouq.order, o...)
	return ouq
}

// QueryUser chains the current query on the "user" edge.
func (ouq *ObjectUserQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: ouq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ouq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ouq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(objectuser.Table, objectuser.UserColumn, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, objectuser.UserTable, objectuser.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(ouq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryObject chains the current query on the "object" edge.
func (ouq *ObjectUserQuery) QueryObject() *ObjectQuery {
	query := (&ObjectClient{config: ouq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ouq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ouq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(objectuser.Table, objectuser.ObjectColumn, selector),
			sqlgraph.To(object.Table, object.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, objectuser.ObjectTable, objectuser.ObjectColumn),
		)
		fromU = sqlgraph.SetNeighbors(ouq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ObjectUser entity from the query.
// Returns a *NotFoundError when no ObjectUser was found.
func (ouq *ObjectUserQuery) First(ctx context.Context) (*ObjectUser, error) {
	nodes, err := ouq.Limit(1).All(setContextOp(ctx, ouq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{objectuser.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ouq *ObjectUserQuery) FirstX(ctx context.Context) *ObjectUser {
	node, err := ouq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// Only returns a single ObjectUser entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ObjectUser entity is found.
// Returns a *NotFoundError when no ObjectUser entities are found.
func (ouq *ObjectUserQuery) Only(ctx context.Context) (*ObjectUser, error) {
	nodes, err := ouq.Limit(2).All(setContextOp(ctx, ouq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{objectuser.Label}
	default:
		return nil, &NotSingularError{objectuser.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ouq *ObjectUserQuery) OnlyX(ctx context.Context) *ObjectUser {
	node, err := ouq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// All executes the query and returns a list of ObjectUsers.
func (ouq *ObjectUserQuery) All(ctx context.Context) ([]*ObjectUser, error) {
	ctx = setContextOp(ctx, ouq.ctx, "All")
	if err := ouq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ObjectUser, *ObjectUserQuery]()
	return withInterceptors[[]*ObjectUser](ctx, ouq, qr, ouq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ouq *ObjectUserQuery) AllX(ctx context.Context) []*ObjectUser {
	nodes, err := ouq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// Count returns the count of the given query.
func (ouq *ObjectUserQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ouq.ctx, "Count")
	if err := ouq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ouq, querierCount[*ObjectUserQuery](), ouq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ouq *ObjectUserQuery) CountX(ctx context.Context) int {
	count, err := ouq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ouq *ObjectUserQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ouq.ctx, "Exist")
	switch _, err := ouq.First(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ouq *ObjectUserQuery) ExistX(ctx context.Context) bool {
	exist, err := ouq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ObjectUserQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ouq *ObjectUserQuery) Clone() *ObjectUserQuery {
	if ouq == nil {
		return nil
	}
	return &ObjectUserQuery{
		config:     ouq.config,
		ctx:        ouq.ctx.Clone(),
		order:      append([]OrderFunc{}, ouq.order...),
		inters:     append([]Interceptor{}, ouq.inters...),
		predicates: append([]predicate.ObjectUser{}, ouq.predicates...),
		withUser:   ouq.withUser.Clone(),
		withObject: ouq.withObject.Clone(),
		// clone intermediate query.
		sql:  ouq.sql.Clone(),
		path: ouq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (ouq *ObjectUserQuery) WithUser(opts ...func(*UserQuery)) *ObjectUserQuery {
	query := (&UserClient{config: ouq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ouq.withUser = query
	return ouq
}

// WithObject tells the query-builder to eager-load the nodes that are connected to
// the "object" edge. The optional arguments are used to configure the query builder of the edge.
func (ouq *ObjectUserQuery) WithObject(opts ...func(*ObjectQuery)) *ObjectUserQuery {
	query := (&ObjectClient{config: ouq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ouq.withObject = query
	return ouq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID puuid.ID `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ObjectUser.Query().
//		GroupBy(objectuser.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ouq *ObjectUserQuery) GroupBy(field string, fields ...string) *ObjectUserGroupBy {
	ouq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ObjectUserGroupBy{build: ouq}
	grbuild.flds = &ouq.ctx.Fields
	grbuild.label = objectuser.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID puuid.ID `json:"user_id,omitempty"`
//	}
//
//	client.ObjectUser.Query().
//		Select(objectuser.FieldUserID).
//		Scan(ctx, &v)
func (ouq *ObjectUserQuery) Select(fields ...string) *ObjectUserSelect {
	ouq.ctx.Fields = append(ouq.ctx.Fields, fields...)
	sbuild := &ObjectUserSelect{ObjectUserQuery: ouq}
	sbuild.label = objectuser.Label
	sbuild.flds, sbuild.scan = &ouq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ObjectUserSelect configured with the given aggregations.
func (ouq *ObjectUserQuery) Aggregate(fns ...AggregateFunc) *ObjectUserSelect {
	return ouq.Select().Aggregate(fns...)
}

func (ouq *ObjectUserQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ouq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ouq); err != nil {
				return err
			}
		}
	}
	for _, f := range ouq.ctx.Fields {
		if !objectuser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ouq.path != nil {
		prev, err := ouq.path(ctx)
		if err != nil {
			return err
		}
		ouq.sql = prev
	}
	return nil
}

func (ouq *ObjectUserQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ObjectUser, error) {
	var (
		nodes       = []*ObjectUser{}
		_spec       = ouq.querySpec()
		loadedTypes = [2]bool{
			ouq.withUser != nil,
			ouq.withObject != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ObjectUser).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ObjectUser{config: ouq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(ouq.modifiers) > 0 {
		_spec.Modifiers = ouq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ouq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ouq.withUser; query != nil {
		if err := ouq.loadUser(ctx, query, nodes, nil,
			func(n *ObjectUser, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := ouq.withObject; query != nil {
		if err := ouq.loadObject(ctx, query, nodes, nil,
			func(n *ObjectUser, e *Object) { n.Edges.Object = e }); err != nil {
			return nil, err
		}
	}
	for i := range ouq.loadTotal {
		if err := ouq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ouq *ObjectUserQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*ObjectUser, init func(*ObjectUser), assign func(*ObjectUser, *User)) error {
	ids := make([]puuid.ID, 0, len(nodes))
	nodeids := make(map[puuid.ID][]*ObjectUser)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (ouq *ObjectUserQuery) loadObject(ctx context.Context, query *ObjectQuery, nodes []*ObjectUser, init func(*ObjectUser), assign func(*ObjectUser, *Object)) error {
	ids := make([]puuid.ID, 0, len(nodes))
	nodeids := make(map[puuid.ID][]*ObjectUser)
	for i := range nodes {
		fk := nodes[i].ObjectID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(object.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "object_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ouq *ObjectUserQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ouq.querySpec()
	if len(ouq.modifiers) > 0 {
		_spec.Modifiers = ouq.modifiers
	}
	_spec.Unique = false
	_spec.Node.Columns = nil
	return sqlgraph.CountNodes(ctx, ouq.driver, _spec)
}

func (ouq *ObjectUserQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(objectuser.Table, objectuser.Columns, nil)
	_spec.From = ouq.sql
	if unique := ouq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ouq.path != nil {
		_spec.Unique = true
	}
	if fields := ouq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		for i := range fields {
			_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
		}
	}
	if ps := ouq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ouq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ouq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ouq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ouq *ObjectUserQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ouq.driver.Dialect())
	t1 := builder.Table(objectuser.Table)
	columns := ouq.ctx.Fields
	if len(columns) == 0 {
		columns = objectuser.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ouq.sql != nil {
		selector = ouq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ouq.ctx.Unique != nil && *ouq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ouq.predicates {
		p(selector)
	}
	for _, p := range ouq.order {
		p(selector)
	}
	if offset := ouq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ouq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ObjectUserGroupBy is the group-by builder for ObjectUser entities.
type ObjectUserGroupBy struct {
	selector
	build *ObjectUserQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ougb *ObjectUserGroupBy) Aggregate(fns ...AggregateFunc) *ObjectUserGroupBy {
	ougb.fns = append(ougb.fns, fns...)
	return ougb
}

// Scan applies the selector query and scans the result into the given value.
func (ougb *ObjectUserGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ougb.build.ctx, "GroupBy")
	if err := ougb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ObjectUserQuery, *ObjectUserGroupBy](ctx, ougb.build, ougb, ougb.build.inters, v)
}

func (ougb *ObjectUserGroupBy) sqlScan(ctx context.Context, root *ObjectUserQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ougb.fns))
	for _, fn := range ougb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ougb.flds)+len(ougb.fns))
		for _, f := range *ougb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ougb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ougb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ObjectUserSelect is the builder for selecting fields of ObjectUser entities.
type ObjectUserSelect struct {
	*ObjectUserQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ous *ObjectUserSelect) Aggregate(fns ...AggregateFunc) *ObjectUserSelect {
	ous.fns = append(ous.fns, fns...)
	return ous
}

// Scan applies the selector query and scans the result into the given value.
func (ous *ObjectUserSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ous.ctx, "Select")
	if err := ous.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ObjectUserQuery, *ObjectUserSelect](ctx, ous.ObjectUserQuery, ous, ous.inters, v)
}

func (ous *ObjectUserSelect) sqlScan(ctx context.Context, root *ObjectUserQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ous.fns))
	for _, fn := range ous.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ous.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ous.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
