// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// City is the predicate function for city builders.
type City func(*sql.Selector)

// Collection is the predicate function for collection builders.
type Collection func(*sql.Selector)

// Object is the predicate function for object builders.
type Object func(*sql.Selector)

// ObjectUser is the predicate function for objectuser builders.
type ObjectUser func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
