services:
  go:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
      target: dev
    restart: unless-stopped
    ports:
      - "7070:3000"
    env_file: ./.env
    volumes:
      - .:/radioatelier
      - -../uploads:/radioatelier/assets/uploads
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: radioatelier
    volumes:
      - ./docker/mysql/data:/var/lib/mysql

  manticore:
    container_name: manticore
    image: manticoresearch/manticore
    restart: always
    ports:
      - "127.0.0.1:9306:9306"
      - "127.0.0.1:9308:9308"
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker/manticore/data:/var/lib/manticore
      - ./docker/manticore/manticore.conf:/etc/manticoresearch/manticore.conf
